parameters:
#    maria_magdalena_test.example.class: MariaMagdalena\TestBundle\Example

services:
#    maria_magdalena_test.example:
#        class: %maria_magdalena_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
